// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://objcamdamhivmznrmhrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iamNhbWRhbWhpdm16bnJtaHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDA1NDMsImV4cCI6MjA2NzYxNjU0M30.ZbnFhpSX1rZ8EqDpTUesKAPXM-onMB9G0EnuVda8L2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});